# All roles are installed from Ansible Galaxy
- bearandgiraffe.yarn
- DavidWittman.redis
- geerlingguy.nginx
- geerlingguy.nodejs
- geerlingguy.postgresql
- hashbangcode.imagemagick
- kamaln7.swapfile
- manala.fail2ban
- manala.git
- manala.zsh
- mashimom.oh-my-zsh
- rvm.ruby
- pgolm.monit
