- name: Setup user environment
  hosts: rails
  remote_user: deploy
  roles:
    - mashimom.oh-my-zsh

- name: Install all necessary software
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - common-software
    - manala.fail2ban
    - geerlingguy.nodejs

- name: Add swap file
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 2GB
      swapfile_swappiness: 10
      swapfile_location: /mnt/swapfile_2GB

- name: Setup nginx
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: geerlingguy.nginx
      nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf.j2"
      nginx_vhost_template: "{{ playbook_dir }}/templates/vhost.j2"

- name: Setup ImageMagick
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - hashbangcode.imagemagick

- name: Setup yarn
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - bearandgiraffe.yarn

- name: Setup Rust for faster_path gem
  hosts: rails
  remote_user: deploy
  roles:
    - rust

- name: Install redis
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: DavidWittman.redis
      redis_bind: 127.0.0.1

- name: Install Ruby
  hosts: rails
  remote_user: deploy
  roles:
    - role: rvm_io.ruby
      rvm1_user: deploy
      become: yes
      rvm1_rubies:
        - "ruby-{{ ruby_version }}"
    - ruby

- name: Install PostgreSQL
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: geerlingguy.postgresql
      postgresql_version: 9.5
      postgresql_locales:
        - 'en_US.UTF-8'
      postgresql_users:
        - name: deploy
          password: "{{ postgres_password }}"
          role_attr_flags: SUPERUSER

- name: Setup monit
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: wtanaka.monit
      when: (monit_enabled is defined) and monit_enabled

- name: Setup certbot
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - setup-certbot
