- name: Install requirements
  apt:
    name: software-properties-common

- name: Update repositories cache and install certbot
  apt:
    update_cache: yes
    name: certbot

- name: Upload cli.ini
  template:
    src: templates/cli.ini
    dest: /etc/letsencrypt/cli.ini

- name: Register in certbot
  command: "certbot register --email {{ letsencrypt_email }} --agree-tos --no-eff-email"
  become_user: root
  become: yes
  ignore_errors: yes
